# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8086dca99f73d36a6fcbcf65a862632acbf16a2a8b7cce7da8f922ad39ef0724de64c096333e82ac4282697312d0437dc2e66a0a422f633956ef129434e339dc

test:
  secret_key_base: 8211a3054df1fd4eda1cbf356887be6d30c8dcf77cc0a200930180321e69a13bbba30a6c42042cee15edc2c0405a4bd2ab61d6989e3311083206592bcd85f214

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
